[package]
name = "ray-tracing-in-a-weekend"
version = "0.1.0"
authors = ["Aditya Arora <10962267+arora-aditya@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rayon = "1.2.1"