#[path = "texture.rs"]
pub mod texture;
#[path = "solid_color.rs"]
pub mod solid_color;
#[path = "checkers_texture.rs"]
pub mod checkers_texture;
#[path = "perlin.rs"]
pub mod perlin;
#[path = "noise.rs"]
pub mod noise;
#[path = "image.rs"]
pub mod image;